name: spec
on:
  push:
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 6 * * 6" # Every Saturday 6 AM
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1.8.0
        with:
          crystal: latest
      - name: Check formatting
        run: crystal tool format --check
  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        crystal: [1.6.2, 1.7.2, 1.8.1, latest]
        adapter: [mysql, pg, sqlite]
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:10.4
        # Provide the password for postgres
        env:
          POSTGRES_USER: granite
          POSTGRES_PASSWORD: password
          POSTGRES_DB: granite_db
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: granite_db
          MYSQL_USER: granite
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1.8.0
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards update --ignore-crystal-version
      - name: Run tests
        run: crystal spec --order=random
        env:
          CURRENT_ADAPTER: ${{ matrix.adapter }}
          SQLITE_DATABASE_URL: sqlite3:./granite.db
          MYSQL_DATABASE_URL: mysql://granite:password@postgres:3306/granite_db
          PG_DATABASE_URL: postgres://granite:password@mysql:5432/granite_db
